### ISSUE TITLE
How to handle the group application?

### ISSUE THREAD

**Issue by leemaomaomao** [uxDaniel/visa_rescheduler#22]
when create group appointment with 2 ppl, it will stuck as below errors
https://ais.usvisa-info.com/en-ca/niv/groups/<groupid>

And app give below:
Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x005437D3]
        (No symbol) [0x004D8B81]
        (No symbol) [0x003DB36D]
        (No symbol) [0x0040D382]
        (No symbol) [0x0040D4BB]
        (No symbol) [0x00443302]
        (No symbol) [0x0042B464]
        (No symbol) [0x00441215]
        (No symbol) [0x0042B216]
        (No symbol) [0x00400D97]
        (No symbol) [0x0040253D]
        GetHandleVerifier [0x007BABF2+2510930]
        GetHandleVerifier [0x007E8EC1+2700065]
        GetHandleVerifier [0x007EC86C+2714828]
        GetHandleVerifier [0x005F3480+645344]
        (No symbol) [0x004E0FD2]
        (No symbol) [0x004E6C68]
        (No symbol) [0x004E6D4B]
        (No symbol) [0x004F0D6B]
        BaseThreadInitThunk [0x75DA00F9+25]
        RtlGetAppContainerNamedObjectPath [0x76FE7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x76FE7B8E+238]

**Comment by lernik44** [comment]
@leemaomaomao Can you please share how you solved this problem?

**Comment by Arsh20101** [comment]
@leemaomaomao @lernik44 were you able to solve this?

**Comment by lernik44** [comment]
> @leemaomaomao @lernik44 were you able to solve this?

Unfortunately not :(
