### ISSUE TITLE
Question: what do the constant DAYS_IN_COUNTRY

### ISSUE THREAD

**Issue by israteneda** [uxDaniel/visa_rescheduler#3]
Hello 👋 nice project.
I have a question, what does `DAYS_IN_COUNTRY` refer to?

**Comment by theadri2** [comment]
Hey, that's the ID of the facility where you want to do the appointment. You can easily check that by analyzing any request in the reschedule page

**Comment by israteneda** [comment]
Got it, @theadri2 thanks for the answer

**Comment by uxDaniel** [comment]
Thank you all, I will update the variable name to better reflect its purpose.
