### ISSUE TITLE
A beginner's question

### ISSUE THREAD

**Issue by JimCoala** [uxDaniel/visa_rescheduler#30]
I am a beginner in Python, I have installed requirements.txt, and reported this error when running this visa.py, I want to know how to solve it, thank you!

![Gibhub issue](https://user-images.githubusercontent.com/130429847/231059308-55878756-deac-4216-905d-4114f7cfba43.jpg)

**Comment by Soroosh-N** [comment]
> 

Hi,
After setting the config file, please remove the ".example" from your "config.ini.example" file. The final file would be "config.ini"
I think that's the problem and after that, you are all set.

**Comment by JimCoala** [comment]
> 



> > 
> 
> Hi, After setting the config file, please remove the ".example" from your "config.ini.example" file. The final file would be "config.ini" I think that's the problem and after that, you are all set.

Thank you very much, it is work!
