### ISSUE TITLE
JSON URLs for checking dates and times are no longer valid

### ISSUE THREAD

**Issue by liuyang12** [uxDaniel/visa_rescheduler#31]
It seems that JSON URLs shown below are no longer valid. Any one have solutions or suggestions to check the available dates and times for each consulate and ASC appointment?

https://github.com/uxDaniel/visa_rescheduler/blob/b2bc1b0bc335953a0facb60fb957cc5324d08947/visa.py#L50-L52

same issue on another repo: https://github.com/theoomoregbee/US-visa-appointment-notifier/issues/25

**Comment by mandeepjandoria** [comment]
Looks like they have implemented some sort of authentication/authorization to consume this api.

**Comment by liuyang12** [comment]
works by adding extra http headings to the selenium driver, as fixed by @ficusun https://github.com/theoomoregbee/US-visa-appointment-notifier/issues/25#issuecomment-1518723568

The python version works as shown below:
0. install `selenium-wire` to add extra http headings via `pip install selenium-wire`.
1. replace the following line with `from seleniumwire import webdriver`. https://github.com/uxDaniel/visa_rescheduler/blob/b2bc1b0bc335953a0facb60fb957cc5324d08947/visa.py#L11
2. add the following lines after `driver = get_driver()` https://github.com/uxDaniel/visa_rescheduler/blob/b2bc1b0bc335953a0facb60fb957cc5324d08947/visa.py#L91
```python
def interceptor(request):
    request.headers['Accept'] = 'application/json, text/javascript, */*; q=0.01'
    request.headers['X-Requested-With'] = 'XMLHttpRequest'
    
driver.request_interceptor = interceptor
```
